
ALTER TABLE `plazastore` DROP COLUMN `FridayClosingTime`,
    DROP COLUMN `FridayOpeningTime`,
    DROP COLUMN `MondayClosingTime`,
    DROP COLUMN `MondayOpeningTime`,
    DROP COLUMN `SaturdayClosingTime`,
    DROP COLUMN `SaturdayOpeningTime`,
    DROP COLUMN `SundayClosingTime`,
    DROP COLUMN `SundayOpeningTime`,
    DROP COLUMN `ThursdayClosingTime`,
    DROP COLUMN `ThursdayOpeningTime`,
    DROP COLUMN `TuesdayClosingTime`,
    DROP COLUMN `TuesdayOpeningTime`,
    DROP COLUMN `WednesdayClosingTime`,
    DROP COLUMN `WednesdayOpeningTime`,
    ADD COLUMN `closingTime` VARCHAR(191) NOT NULL,
    ADD COLUMN `openingTime` VARCHAR(191) NOT NULL;
